pipeline {
    agent any

  tools {
        jdk 'JDK_1.8'  // Jenkins 관리 페이지에서 설정한 JDK 이름과 일치해야 합니다.
    }


    stages {
        stage('Checkout') {
            steps {
                // 소스코드 체크아웃
                checkout scm
            }
        }

        stage('Build') {
                steps {
                // Java 파일들을 컴파일하여 생성된 클래스 파일을 classes 디렉토리에 저장
                // window 일 경우 bat
                sh 'javac -encoding UTF-8 -classpath "libs/*" -d classes UnitTest/src/*.java'
           }
        }

        stage('Test') {
            steps {
                script {
                    // JUnit 5 테스트 실행을 위한 classpath 설정
                    def classpath = "classes:libs/*"
                    // JUnit 5 테스트 실행
                    sh 'java -cp ${classpath} org.junit.platform.console.ConsoleLauncher --scan-classpath > test_results.txt'
                    }
                }
         }
    }

    post {
        always {
            // 테스트 결과 파일을 저장하기 위해 아카이브
            archiveArtifacts 'test_results.txt'
        }
        failure {
            echo 'Build or test failed'
        }
        success {
            echo 'Build and test succeeded'
        }
    }
}



